// === BEGIN: Original tsd_library.js ===
// tsd_library.js — Exhaustif (BT <1000V, ATEX, HT >1000V) + identification claire UPS/Battery
// Mapping strictement aligné avec les types utilisés par server_controls.js

export const EQUIPMENT_TYPES = [
  'LV_SWITCHBOARD',   // Tableaux BT < 1000V (TGBT, TD)
  'LV_DEVICE',        // Départs/disjoncteurs/DDR montés dans tableaux BT
  'ATEX_EQUIPMENT',   // Matériels en zones ATEX
  'HV_EQUIPMENT',     // Cellules / Switchgear HT >1000V (y.c. TF, disjoncteurs, relais, SF6…)
  'UPS',              // UPS (marqué non couvert par défaut)
  'BATTERY_SYSTEM'    // Batteries / racks (marqué non couvert par défaut)
];

// Utilitaires courants
const YES = true;
const NO  = false;

// Pour UPS/BATTERY : indicateur pour le backend (si false => classer en not_present)
export const TSD_FLAGS = {
  UPS: { enabled: false, note: 'Non couvert TSD actuel. À construire ultérieurement.' },
  BATTERY_SYSTEM: { enabled: false, note: 'Non couvert TSD actuel. À construire ultérieurement.' }
};

export const TSD_LIBRARY = {

  // =====================================================================
  // LV — SWITCHBOARD (< 1000V) : TGBT, tableaux divisionnaires, busbar
  // =====================================================================
  LV_SWITCHBOARD: [
    {
      id: 'lv_room_clean_dry',
      label: 'Local propre, sec, ventilé',
      field: 'lv_room_clean_dry',
      type: 'check',
      comparator: '==',
      threshold: YES,
      frequency_months: 3,
      procedure_md: 'Inspection visuelle du local (poussière, humidité, fuites, ventilation). Vérifier que nulle obstruction gêne la dissipation thermique.',
      hazards_md: 'Choc électrique, arc en cas de pollution/condensation.',
      ppe_md: 'Gants isolants cat. adaptée, lunettes.',
      tools_md: 'Lampe, caméra thermique (optionnelle).'
    },
    {
      id: 'lv_covers_doors_labels',
      label: 'Capots/portes/serrures/plaques signalétique',
      field: 'lv_panels_integrity',
      type: 'check',
      comparator: '==',
      threshold: YES,
      frequency_months: 6,
      procedure_md: 'Vérifier l’intégrité, la fixation, les verrous/clefs et la lisibilité des étiquettes/cadenassage.',
      hazards_md: 'Contact direct si capot manquant, coupure intempestive.',
      ppe_md: 'Gants, lunettes.',
      tools_md: 'Tournevis/clé isolée.'
    },
    {
      id: 'lv_thermography',
      label: 'Thermographie sous charge',
      field: 'lv_ir_max_delta',
      type: 'number',
      unit: '°C',
      comparator: '<=',
      threshold: 25,
      frequency_months: 12,
      procedure_md: 'Effectuer une thermographie en charge nominale. Tolérer ΔT ≤ 25°C entre connexions homogènes. Au-delà, investiguer serrage/oxydation.',
      hazards_md: 'Brûlure, exposition arc si enlèvement capots.',
      ppe_md: 'Visière/écran facial, gants ignifugés selon risque.',
      tools_md: 'Caméra IR étalonnée.'
    },
    {
      id: 'lv_torque_check',
      label: 'Re-serrage connexions principales',
      field: 'lv_torque_ok',
      type: 'check',
      comparator: '==',
      threshold: YES,
      frequency_months: 24,
      procedure_md: 'Contrôle couple sur jeux de barres/borniers selon couples constructeur. Si couple non disponible, appliquer référentiel interne et consigner.',
      hazards_md: 'Arc à l’ouverture, serrage sur pièces sous tension interdit.',
      ppe_md: 'Gants isolants, lunettes.',
      tools_md: 'Clé dynamométrique isolée.'
    },
    {
      id: 'lv_insulation_resistance',
      label: 'Mesure de résistance d’isolement tableau',
      field: 'lv_ir_value',
      type: 'number',
      unit: 'MΩ',
      comparator: '>=',
      threshold: 1,
      frequency_months: 36,
      procedure_md: 'Mesurer l’isolement phase/terre et phase/phase selon procédure. Seuil minimal 1 MΩ (ou conforme note constructeur/site).',
      hazards_md: 'Injection de tension d’essai, déconnexion préalable requise.',
      ppe_md: 'Gants isolants, lunettes.',
      tools_md: 'Mégohmmètre.'
    },
    {
      id: 'lv_rcd_test',
      label: 'Test déclenchement DDR/RCD (bouton Test ou injecteur)',
      field: 'lv_rcd_trip',
      type: 'check',
      comparator: '==',
      threshold: YES,
      frequency_months: 12,
      procedure_md: 'Actionner bouton TEST ou injecter IΔn pour vérifier déclenchement dans le temps spécifié.',
      hazards_md: 'Coupure de circuits sensibles.',
      ppe_md: 'Aucun spécifique (prévenir utilisateurs).',
      tools_md: 'Injecteur DDR (si disponible).'
    },
    {
      id: 'lv_earthing_continuity',
      label: 'Continuité de la liaison équipotentielle',
      field: 'lv_pe_continuity',
      type: 'check',
      comparator: '==',
      threshold: YES,
      frequency_months: 12,
      procedure_md: 'Vérifier continuité PE entre carcasses/portes/rails et barres PE.',
      hazards_md: 'Risque choc si absence de PE.',
      ppe_md: 'Gants, lunettes.',
      tools_md: 'Ohmmètre faible courant.'
    }
  ],

  // =====================================================================
  // LV — DEVICES (< 1000V) : Départs, disjoncteurs, sectionneurs, VSD, etc.
  // =====================================================================
  LV_DEVICE: [
    {
      id: 'dev_visual_mechanical',
      label: 'État visuel & mécanique (poignées, indicateurs)',
      field: 'dev_visual_ok',
      type: 'check',
      comparator: '==',
      threshold: YES,
      frequency_months: 12,
      procedure_md: 'Vérifier indicateurs (ouvert/fermé), verrouillage, position, étiquetage, câblage apparent.',
      hazards_md: 'Contact direct si capot/vis manquants.',
      ppe_md: 'Gants, lunettes.',
      tools_md: 'Tournevis isolé.'
    },
    {
      id: 'dev_functional_test',
      label: 'Essai fonctionnel (déclencheur/disjoncteur) hors charge',
      field: 'dev_trip_ok',
      type: 'check',
      comparator: '==',
      threshold: YES,
      frequency_months: 24,
      procedure_md: 'Tester le déclenchement mécanique (si possible). Ne pas endommager sélectivité/production. Consigner temps/observations.',
      hazards_md: 'Coupure inattendue si mal isolé du réseau.',
      ppe_md: 'Gants, lunettes.',
      tools_md: 'Injecteur secondaire (si relais), chronomètre.'
    },
    {
      id: 'dev_thermography',
      label: 'Thermographie sur bornes du départ',
      field: 'dev_ir_max_delta',
      type: 'number',
      unit: '°C',
      comparator: '<=',
      threshold: 20,
      frequency_months: 12,
      procedure_md: 'Caméra IR sur bornes du départ en charge. ΔT ≤ 20°C. Sinon, contrôler serrage/oxydation.',
      hazards_md: 'Brûlure/arc si capots retirés sous charge.',
      ppe_md: 'Visière, gants ignifugés si risque.',
      tools_md: 'Caméra IR.'
    },
    {
      id: 'dev_rcd',
      label: 'Si DDR intégré : test de déclenchement',
      field: 'dev_rcd_trip',
      type: 'check',
      comparator: '==',
      threshold: YES,
      frequency_months: 12,
      procedure_md: 'Appuyer test ou injecter IΔn, vérifier déclenchement et temps.',
      hazards_md: 'Perte alimentation circuits aval.',
      ppe_md: 'Aucun spécifique.',
      tools_md: 'Injecteur DDR.'
    }
  ],

  // =====================================================================
  // ATEX — ZONES EXPLOSIVES (Ex d/e/i/n/t) : Matériels marqués Ex
  // =====================================================================
  ATEX_EQUIPMENT: [
    {
      id: 'atex_visual_external',
      label: 'Inspection visuelle externe (Cat. 1/2/3) — rapproché',
      field: 'atex_ext_visual_ok',
      type: 'check',
      comparator: '==',
      threshold: YES,
      frequency_months: 6,
      procedure_md: 'Contrôler enveloppes, presse-étoupes, garnitures, corrosion, chocs, marquage CE/Ex lisible, IP adapté à la zone.',
      hazards_md: 'Risque d’explosion (empêcher toute source d’ignition).',
      ppe_md: 'Chaussures antistatiques, tenue antistatique, ESD si requis.',
      tools_md: 'Lampe ATEX, clé dynamométrique ATEX.'
    },
    {
      id: 'atex_detailed_internal',
      label: 'Inspection détaillée (ouverture) selon mode de protection',
      field: 'atex_detailed_ok',
      type: 'check',
      comparator: '==',
      threshold: YES,
      frequency_months: 12,
      procedure_md: 'Ouvrir si autorisé (Ex e/d). Vérifier jeux d’air, joints, surfaces de contact Ex d, serrage bornes, continuité PE.',
      hazards_md: 'Perte de confinement Ex d, risque inflammation.',
      ppe_md: 'Gants, lunettes, ESD si électronique.',
      tools_md: 'Clé dynamométrique ATEX, multimètre, jauges.'
    },
    {
      id: 'atex_bonding_earthing',
      label: 'Liaisons équipotentielles & terre',
      field: 'atex_pe_ok',
      type: 'check',
      comparator: '==',
      threshold: YES,
      frequency_months: 12,
      procedure_md: 'Vérifier continuité PE, pontages, ponts de terre sur presse-étoupes métalliques, serrage.',
      hazards_md: 'Charge électrostatique non évacuée.',
      ppe_md: 'Gants, lunettes.',
      tools_md: 'Ohmmètre faible courant.'
    }
  ],

  // =====================================================================
  // HV — > 1000V : Switchgear HT, Transformateurs, Disjoncteurs, Relais, SF6
  // =====================================================================
  HV_EQUIPMENT: [
    {
      id: 'hv_room_clean_dry',
      label: 'Local HT propre, sec, verrouillé',
      field: 'hv_room_ok',
      type: 'check',
      comparator: '==',
      threshold: YES,
      frequency_months: 3,
      procedure_md: 'Inspection du local HT : propreté, absence d’humidité, verrouillage, absence d’intrusions.',
      hazards_md: 'Arc HT (danger mortel), claquages.',
      ppe_md: 'Casque, visière, gants isolants HT, vêtements ignifugés.',
      tools_md: 'Lampe, caméra IR (option).'
    },
    {
      id: 'hv_cb_timing',
      label: 'Essai temporisation disjoncteur HT',
      field: 'hv_cb_time_ms',
      type: 'number',
      unit: 'ms',
      comparator: '<=',
      threshold: 80,
      frequency_months: 24,
      procedure_md: 'Mesure des temps d’ouverture/fermeture sous injecteur secondaire selon constructeur. Comparer au référentiel.',
      hazards_md: 'Mauvaise manœuvre peut endommager l’appareil.',
      ppe_md: 'Gants isolants HT, lunettes.',
      tools_md: 'Injecteur secondaire, chronomètre/temporographe.'
    },
    {
      id: 'hv_protection_relay_test',
      label: 'Test relais de protection (secondaire)',
      field: 'hv_relay_trip_ok',
      type: 'check',
      comparator: '==',
      threshold: YES,
      frequency_months: 12,
      procedure_md: 'Injection secondaire pour vérifier tripping/paramètres, en respectant sélectivité & consignation.',
      hazards_md: 'Déclenchement intempestif si mauvais câblage.',
      ppe_md: 'Gants, lunettes.',
      tools_md: 'Injecteur secondaire, PC logiciel si numérique.'
    },
    {
      id: 'hv_sf6_density',
      label: 'Contrôle densité SF₆',
      field: 'hv_sf6_density_ok',
      type: 'check',
      comparator: '==',
      threshold: YES,
      frequency_months: 12,
      procedure_md: 'Relever densité/pression SF₆ vs température. En cas d’écart, consigner et programmer maintenance.',
      hazards_md: 'Fuite de gaz, risque environnemental.',
      ppe_md: 'Gants, lunettes.',
      tools_md: 'Densimètre/lecteur fabricant.'
    },
    {
      id: 'tf_oil_dga',
      label: 'Transformateur — DGA (analyse gaz dissous) / rigidité diélectrique',
      field: 'tf_oil_dga_ok',
      type: 'check',
      comparator: '==',
      threshold: YES,
      frequency_months: 12,
      procedure_md: 'Prélèvement huile : DGA, rigidité diélectrique, BF/BG, eau/ppm. Comparer aux seuils alerte.',
      hazards_md: 'Brûlure huile chaude, pollution.',
      ppe_md: 'Gants, lunettes, combinaison anti-huile.',
      tools_md: 'Kit prélèvement, flacons labo.'
    },
    {
      id: 'tf_thermography',
      label: 'Transformateur — thermographie connexions/évents',
      field: 'tf_ir_delta',
      type: 'number',
      unit: '°C',
      comparator: '<=',
      threshold: 25,
      frequency_months: 12,
      procedure_md: 'Thermographie sur bornes BT/HT, radiateurs, connexions ; ΔT ≤ 25°C.',
      hazards_md: 'Brûlure/arc.',
      ppe_md: 'Visière/écran, gants ignifugés.',
      tools_md: 'Caméra IR.'
    },
    {
      id: 'tf_tan_delta',
      label: 'Transformateur — tangente delta/isolement',
      field: 'tf_tandelta',
      type: 'number',
      unit: '%',
      comparator: '<=',
      threshold: 1.0,
      frequency_months: 36,
      procedure_md: 'Mesure tan δ selon norme/constructeur, comparer aux historiques.',
      hazards_md: 'Tension d’essai élevée.',
      ppe_md: 'Gants isolants HT.',
      tools_md: 'Pont de mesure tan δ.'
    }
  ],

  // =====================================================================
  // UPS (non couvert TSD — volontairement marqué pour not_present)
  // =====================================================================
  UPS: [
    {
      id: 'ups_placeholder',
      label: 'UPS — non couvert (à construire)',
      field: 'ups_placeholder',
      type: 'check',
      comparator: '==',
      threshold: NO,
      frequency_months: 12,
      procedure_md: 'À définir ultérieurement.',
      hazards_md: '—',
      ppe_md: '—',
      tools_md: '—'
    }
  ],

  // =====================================================================
  // BATTERY SYSTEM (non couvert TSD — volontairement marqué pour not_present)
  // =====================================================================
  BATTERY_SYSTEM: [
    {
      id: 'bat_placeholder',
      label: 'Batteries — non couvert (à construire)',
      field: 'bat_placeholder',
      type: 'check',
      comparator: '==',
      threshold: NO,
      frequency_months: 12,
      procedure_md: 'À définir ultérieurement.',
      hazards_md: '—',
      ppe_md: '—',
      tools_md: '—'
    }
  ]
};

// Normalisation : s’assurer que chaque item a bien ses champs de base
Object.keys(TSD_LIBRARY).forEach(type => {
  TSD_LIBRARY[type].forEach(item => {
    item.type = item.type || 'check';
    item.comparator = item.comparator || '==';
    item.threshold = (item.threshold === undefined) ? YES : item.threshold;
    item.frequency_months = item.frequency_months || 12;
    item.procedure_md = item.procedure_md || 'Procédure standard selon fabricant et consignes site.';
    item.hazards_md = item.hazards_md || 'Risque électrique standard. Respecter consignations.';
    item.ppe_md = item.ppe_md || 'Gants isolants, lunettes.';
    item.tools_md = item.tools_md || 'Outils standard de maintenance.';
  });
});

// === END: Original tsd_library.js ===

// === BEGIN: Auto-integrated full coverage from TSD (generated) ===
// This block is auto-generated from the source PDF to ensure no control line is missed.
// Auto-generated from G2.1 TSD PDF to capture every control line found.
// This file aims for exhaustive coverage of control statements as text lines.
// Source: G2.1 Maintenance, Inspection and Testing of Electrical Equipment TSD.pdf
export const TSD_FULL_CONTROLS = {
  "2 Definitions": [
    "• A certification organisation accredited by a recognised",
    "• Such equipment conforms to the requirements of the Local",
    "The connection of electrical systems to the Earth's conductive surface",
    "control, store, measure or use electrical energy.",
    "In accordance with IEC 60529. Protection against hazardous parts by",
    "• A finger (a jointed test finger of 12mm diameter and",
    "• A solid object of 12.5mm diameter.",
    "protection does not meet IP2X (exposed to touch).",
    "or 600 volts ac (or 900 volts dc) between conductors and earth.",
    "In accordance with IEC 60529. This means protection against ingress",
    "and whether battery or mains powered.",
    "Global Support Function",
    "Partial Discharge",
    "Miniature Circuit Breaker",
  ],
  "3.2.1 Earthing Systems": [
    "Earth Electrode Resistance",
    "a) Inspection",
    "b) Testing",
    "All earth electrodes need to be tested to ensure that good",
    "contact is made with the general mass of earth.",
    "There are several methods for measurement of the earth",
    "The earth electrode resistance should never be above 200",
    "Earth electrode resistance readings must be <100 Ω.",
    "Earthing Conductor Resistance Testing (Continuity",
    "Test)",
    "A low resistance ohmmeter must be used to measure the",
    "Earth System Resistance Value Check",
    "At each stage of the electrical distribution system a check",
    "e.g., Megger DET10C or DET20C.",
    "Maximum resistance to earth values are:",
    "• High Voltage Systems = 1 Ω",
    "• Electrical Power = 5 Ω",
    "• Lightning Protection = 10 Ω",
    "• Electrostatic Discharge = 10 Ω",
    "Lightning protection systems must be inspected to ensure",
    "Lightning Protection Systems.",
    "a) Visual Inspection",
    "• Air termination conductors.",
    "• Down conductors.",
    "• Earth electrode pits.",
    "• Joints.",
    "• Connections.",
    "• Test points.",
    "b) Test",
    "All lightning protection systems must be tested for",
    "continuity using a low resistance milli-ohmmeter e.g.",
    "A resistance value for the whole lightning protection",
    "Earth electrodes should be tested.",
    "• Earth conductor tapes.",
    "• Test points / Earth links.",
    "• Plant items connection to earth.",
    "continuity from plant item to earth link using a low",
  ],
  "3.2.2 High Voltage Switchgear (>1000 V ac)": [
    "Visual Inspection",
    "These inspections are performed with the switchgear",
    "The operator must check that the switchgear is operating",
    "in a clean, cool and dry environment with no abnormal",
    "noises, smells, vibration or heat.",
    "• Arcing can be detected by sound as well as",
    "• The presence of blistered or blackened paint, the",
    "smell of overheated plastic, and the visual",
    "condition of insulation are good indicators of",
    "• Room temperature is a good indication of general",
    "• Storage of combustibles near switchgear.",
    "• Damaged insulators.",
    "• Pooled water, leaks, rodents, and environmental",
    "• Relay indications (flags).",
    "• Voltage readings where possible.",
    "• Current readings where possible.",
    "Thermography",
    "voltage switchgear. Items that must be thermally",
    "a) Busbar chamber covers.",
    "b) Cable Boxes.",
    "c) Voltage Transformers.",
    "a) Perform routine pass / fail partial discharge tests using",
    "a handheld partial discharge equipment e.g.,",
    "Partial Discharge",
    "b) Record results.",
    "c) Failed partial discharge tests must be investigated",
    "a) Check the general condition of the device (Cover,",
    "b) Check the maximum number of operation cycles of the",
    "c) Operate device key locking and operate device pad",
    "d) Check the device racking interlock (operation of the red",
    "e) Operate the racking device manually and / or operate",
    "the racking device electrically for motorized breaker.",
    "f) Operate (Open / Close) the device manually and",
    "Circuit Breaker Maintenance – [Oil, SF6, Vacuum]",
    "Insulation Resistance - Circuit Breaker",
    "Apply 5000Vdc for one minute with the circuit breaker",
    "contacts open and closed to measure phase-to-phase and",
    "phase-to-earth resistance for each pole.",
    "The insulation resistance must be > 2 GΩ.",
    "Vacuum Circuit Breaker Dielectric Over-potential",
    "Perform a dc over-potential test on vacuum circuit breaker",
    "Liquid Screening - Circuit Breaker",
    "b) Moisture: <25ppm.",
    "c) PCB: <50ppm.",
    "a) Dielectric strength: >26 kV.",
    "and test for PCBs, moisture, dielectric strength, and oil",
    "If an oil circuit breaker has cleared a high voltage fault the",
    "Dielectric Over-potential - Circuit Breaker",
    "Contact Resistance - Circuit Breaker",
    "Measure contact resistance of each pole. Compare to",
    "Time Travel - Circuit Breaker",
    "Record the time travel curve for the circuit breaker.",
    "previous test results to determine if there is any",
    "deterioration in the circuit breaker operating mechanism.",
    "Measure the resistance of bolted connections using a low",
    "50% between resistance readings. Also check that the",
    "Apply 5000Vdc for 1-minute to measure phase-to-earth",
    "Insulation Resistance",
    "This inspection is performed with the transformer energised",
    "a) Is the transformer unit in good visual condition i.e., no",
    "b) Is the transformer labelled?",
    "c) Is the transformer locked in the service position?",
    "This inspection is performed with the transformer isolated.",
    "c) Are the busbar and circuit shutters in good condition?",
    "d) If the transformer is withdrawable is the mechanism free",
    "tension and scraping earth are in good condition?",
    "Verify fuse sizes are correct and that the fuses are in good",
    "Check Primary and Secondary Fuses",
    "Apply a dc voltage for one minute to measure the phase-to-",
    "earth resistance on each phase.",
    "The insulation resistance must be >5 GΩ.",
    "Protection Relays",
    "Perform secondary current injection testing to check the",
    "functions of the protection. Check all protective functions",
    "and verify that the relay settings are in accordance with the",
    "protection coordination study.",
  ],
  "3.2.3 Power Factor Correction (>1000 V ac)": [
    "Visual Inspection",
    "a) Check that system is in the correct mode of operation",
    "b) Check controller parameter settings and alarms",
    "c) Check power factor trends and performance of the",
    "Visual Inspection (Once high voltage isolation is in",
    "a) Check capacitors, reactors and cabling for signs of",
    "b) Check capacitor bank cleanliness, ventilation, heating",
    "Capacitor Condition Test (Once high voltage isolation is",
    "a) Carry out capacitor condition tests for each phase on",
    "each step. This test shall include measuring the",
    "capacitance of each capacitor and ensuring the",
    "b) Isolate capacitor banks which fail condition test.",
  ],
  "3 Years": [
    "a) Check for damage.",
    "b) Check rating(s) are correct for capacitor ratings.",
    "c) Check free operation of Vacuum Contactor",
    "d) Ensure fuses are not 'blown'. (Replace with correct",
    "e) Check for evidence of overheating. Renew where",
    "Check all phase and earth connections and terminations.",
    "Check all connections to torque settings recommended by",
  ],
  "3.2.4 Fluid Immersed Transformers": [
    "Visual inspections",
    "a) Check silica gel breathers where necessary replace.",
    "b) Check transformer for signs of abnormality.",
    "c) Check integrity of earthing connections.",
    "Oil Sample Test",
    "a) Carry out oil breakdown voltage, moisture content and",
    "b) Keep a trend of test results. Increase sample testing if",
    "c) Start Conducting FURAN analysis of oil sample for",
    "transformer lifecycle assessment yearly only if a high",
    "b) Keep a trend of DGA results for comparison and",
    "analysis. If fluid fails test investigate and where",
    "a) Carry out fluid screening tests and dissolved gas analysis",
    "(DGA) for main and tap changer tanks.",
    "Inspect Fluid Level",
    "a) Top up fluid where applicable.",
    "b) Make a note of any leaks and arrange for repair.",
    "a) Visual inspection of the temperature indication devices",
    "b) Is unit showing a reasonably expectable temperature",
    "taking into account transformer load profile and",
    "c) Are the temperature alarm and trip settings correct?",
    "d) Record highest temperature peak. Reset peak",
    "a) Visually inspect device for signs of damage or water",
    "Gas and Oil Actuator Relay (Buchholz)",
    "a) Check valves are in correct position.",
    "b) Ensure liquid in chamber.",
    "a) Check unit is in good condition.",
    "c) If gas is present sample the gas for analysis thus",
    "b) Check level has not changed appreciably since last",
    "c) Record levels.",
    "b) Check vacuum or pressure is being maintained and has",
    "c) Record values.",
    "a) Check integrity of cable boxes.",
    "b) Ensure glands are in good condition.",
    "c) Perform routine pass/fail partial discharge tests using a",
    "handheld partial discharge equipment e.g UltraTEV®.",
    "Record results. Failed partial discharge tests must be",
    "a) Visually check cleanliness and condition of bushings.",
    "a) Check condition of fans and guarding.",
    "b) Check the pump housing and gland.",
    "a) Record the number of operations.",
    "c) Ensure the temperature monitors are set to the correct",
    "d) Operate cooling fans and pumps where fitted.",
    "b) Inspect the tap change control panel for signs of",
    "Test – Intrusive Maintenance.",
    "a) Torque checks on bolted connections and fittings.",
    "Where permissible check inside cable boxes for signs of",
    "overheating and partial discharge.",
    "b) Clean and Check bushings for signs of cracks or partial",
    "c) Check cable termination box for signs of water ingress.",
    "Replace gaskets when cable box is opened.",
    "a) Operate ‘Off Circuit Tapping Switch’.",
    "b) Check that the tap switch moves freely across all",
    "Earth Connection Integrity",
    "Earth continuity test must be performed, and results",
    "Insulation Resistance Test",
    "a) Measure the winding to winding and winding to ground",
    "insulation resistance.",
    "b) Insulation resistance measurement must be conducted",
    "c) Insulation resistance readings must be > 100 MΩ on the",
    "d) Results must be recorded.",
    "Low Resistance Test",
    "a) Measure the resistance of bolted connections using a",
    "b) Compare resistance readings between similar bolted",
    "than 50% between resistance readings. Check that the",
    "Power Factor Test on capacitive type bushings",
    "a) Test alarm and tripping functions of all protective",
    "devices associated with transformer. This could include",
    "d) Gas and oil actuator relay (Buchholz).",
    "b) Liquid temperature indicator.",
    "c) Winding temperature indicator.",
    "a) Measure the power factor and capacitance of the high",
    "b) The bushing power factor and capacitance must not vary",
    "test tap is not provided, use the hot collar test and",
    "measure the watts-loss. Bushing hot collar watts-loss",
    "test result.",
    "c) If power factor testing of the bushings is being",
    "performed, it is good practice to extend the test to",
    "include power factor testing of the transformer windings.",
    "De-grease, prepare, prime, undercoat and repaint any",
  ],
  "3.2.5 Cast Resin Transformers": [
    "Visual Inspection – Non-Intrusive Maintenance.",
    "Ventilation and protection devices",
    "a) Look for signs of damage or over heating of wiring to",
    "ventilation and protection devices.",
    "b) Is unit showing a reasonably expectable temperature",
    "taking into account transformer load profile and",
    "c) Perform functional check of protection devices. e.g.,",
    "d) Perform functional check of cooling fans where",
    "a) Check for foreign matter on transformer windings.",
    "b) Vacuum clean and blow less accessible areas with",
    "c) Ensure ventilation grills are free from obstruction.",
    "Check for the correct insulating distances between the",
    "b) Check cable glands are secured and correctly ‘made off’.",
    "Check compliance with original IP rating.",
    "Ingress Protection",
    "a) Check fixings and connections.",
    "Partial Discharge",
    "b) Record results.",
    "a) Perform routine pass/fail partial discharge tests using a",
    "handheld partial discharge equipment e.g. UltraTEV®.",
    "c) Failed partial discharge tests must be investigated",
    "a) Check integrity of cable boxes.",
    "b) Ensure glands are in good condition.",
    "c) Perform routine pass/fail partial discharge tests using a",
    "handheld partial discharge equipment e.g UltraTEV®.",
    "Record results. Failed partial discharge tests must be",
    "a) Check condition of fans and guarding.",
    "b) Ensure the temperature monitors are set to the correct",
    "Test – Intrusive Maintenance",
    "Insulation Resistance Test",
    "Earth Connection Integrity",
    "permissible check inside cable boxes for signs of",
    "overheating and partial discharge.",
    "Earth continuity test must be performed, and results",
    "a) Measure the winding to winding and winding to ground",
    "insulation resistance.",
    "b) Insulation resistance measurement must be conducted",
    "c) Insulation resistance readings must be > 100 MΩ on the",
    "d) Results must be recorded.",
    "Low Resistance Test",
    "a) Measure the resistance of bolted connections using a",
    "b) Compare resistance readings between similar bolted",
    "than 50% between resistance readings. Check that the",
    "Test alarm and tripping functions of all protective devices",
    "associated with transformer. This could include but is not",
    "a) Winding temperature indicator.",
    "b) Over-current Protection Devices.",
    "a) Extend the 1-minute spot insulation resistance test to",
    "include a 10-minute insulation resistance measurement.",
    "5-8 Years Power Factor Test on cast resin transformers over a",
    "b) Calculate the polarization index.",
    "c) This value must not be less than 1.0.",
    "c) Results must be recorded.",
    "a) Measure the power factor of the transformer windings.",
    "b) The CH (high voltage winding) and CHL (high & low",
    "5-8 Years Power Factor Tip-Up Test on cast resin transformers",
    "a) Measure the power factor at increasing test voltages up",
    "to the maximum test voltage.",
    "b) The power factor must remain reasonably constant and",
    "c) Tip-up of over 0.5% warrants investigation and could",
  ],
  "3.2.6 AC Induction Motors >1000 V ac or >400 kW": [
    "Routine Visual Inspection",
    "Using only human senses, check for:",
    "Visually inspect the following:",
    "• Unusual noises.",
    "• Unusual vibrations.",
    "• Excessive heat.",
    "• Oil levels.",
    "• Bearing lubrication leaks.",
    "• Cooling water leaks.",
    "• Blocked air inlet vents.",
    "• Combustibles, and.",
    "• Housekeeping.",
    "• Cable & glanding.",
    "• Fixing bolts.",
    "• Corrosion.",
    "• Chemical attack.",
    "• Physical damage.",
    "• Motor foundations.",
    "• Shaft alignment.",
    "• Earth connections.",
    "• Cooling fan cowling.",
    "• Baffles.",
    "• Motor circuit identification labelling is present and",
    "If online vibration analysis is not provided, perform",
    "vibration measurements of the shaft and bearings. Acoustic",
    "Thermal Imaging",
    "Check the following for signs of overheating:",
    "• Bearings.",
    "• Motor frame.",
    "• Motor terminal box.",
    "• Surge capacitors.",
    "• Cables.",
    "• Motor controller.",
    "• Variable speed drive (VSD).",
    "During insulation testing, perform visual check for",
    "• Water ingress.",
    "• Corona discharge.",
    "b) Polarisation Index (PI)",
    "a) Insulation resistance",
    "Ratio of 10min and 1min insulation resistance test. A",
    "polarisation index (PI) equal to or greater than 2 is an",
    "indication the insulation is clean and dry. However, PI",
    "values much higher than 2 will indicate the insulation is dry",
    "c) DC conductivity",
    "Use a low resistance ohmmeter to measure the resistance",
    "d) Power Factor",
    "Apply an ac voltage and measure the power factor of each",
    "e) Power Factor Tip Up",
    "indicates thermal deterioration.",
    "Measure the power factor of each stator winding phase at",
    "about 20% phase- to-earth voltage and then again at",
    "100% phase- to-earth voltage. The tip-up is the difference",
    "An increasing trend indicates increasing partial discharge",
    "a) Visually inspect for signs of hot spots.",
    "b) Air Gap Measurement.",
    "c) Loop Test.",
    "cooling does not undergo thermal runaway.",
    "a) Insulation resistance.",
    "b) Polarisation Index (PI).",
    "This test is only applicable to wound rotor induction",
    "This test is only applicable to squirrel cage induction",
    "Ratio of 10min and 1min insulation resistance test.",
    "A polarisation index (PI) equal to or greater than 2 is an",
    "values much higher than 2 will indicate the insulation is",
    "c) DC conductivity.",
    "d) Inspect slip rings, brushes and brushes rigging",
    "e) Growler Test.",
    "motor check for signs of corrosion.",
    "Visually inspect for signs of cracking.",
    "NDE of fan blades and vanes for cracking.",
    "This test is only applicable to insulated bearings.",
    "Apply a 500 V dc voltage to the bearings and measure the",
    "resistance to earth.",
    "Minimum insulation resistance of 50MΩ for individual",
    "Minimum insulation resistance of 5MΩ for bearings tested",
    "b) Inspect white metal surfaces of sleeve bearings.",
    "c) Inspect cage and rolling elements of anti-friction",
    "d) Inspect shaft surfaces in contact with bearings.",
    "Check that motor heater is functioning properly.",
  ],
  "3.2.7 Low Voltage Switchgear (<1000 V ac)": [
    "3 months Visual Inspection.",
    "These inspections are performed with the switchgear",
    "The operator must check that the switchgear is operating in",
    "a clean, cool and dry environment with no abnormal noises,",
    "smells, vibration or heat.",
    "a) Arcing can be detected by sound as well as voltage",
    "b) The presence of blistered or blackened paint, the smell",
    "of overheated plastic, and the visual condition of",
    "insulation are good indicators of overheating.",
    "c) Room temperature is a good indication of general",
    "d) Storage of combustibles and unwanted material on or",
    "near switchgear.",
    "e) Damaged insulators.",
    "f) Pooled water, leaks, rodents, and environmental",
    "g) Ensure min IP2X protection against accidental contact",
    "h) All labels must be permanent, legible and accurate to",
    "• Relay indications (flags).",
    "• Voltage readings.",
    "• Current readings.",
    "• Damaged components e.g., displays, meters,",
    "Thermography.",
    "Perform thermographic surveys of low voltage switchgear.",
    "• Solid insulation.",
    "• Bolted connections.",
    "• Switchgear contacts.",
    "• Panel exterior.",
    "• Accessible internal components.",
    "Check the circuit breaker for:",
    "• Smooth operation.",
    "• Correct alignment.",
    "• Mechanical damage.",
    "• Overheating.",
    "• Binding of moving parts.",
    "• Condition of arc chutes.",
    "• Condition of contacts.",
    "• Insulation resistance of main contacts.",
    "• Prove operation of breakers from protection",
    "Also perform a functional check of the charging mechanism",
    "breaker, these auxiliary features can include interlocks and",
    "trip-free, anti-pumping, and trip indicators.)",
    "Functionally test the circuit breaker mechanism and control",
    "Lubricate the circuit breaker in accordance with the",
    "a) Check the circuit breakers for smooth operation and to",
    "confirm the mechanism is not binding and is operating",
    "b) Ensure the protection settings are correct in comparison",
    "a) Mechanically exercise and inspect motor contactors that",
    "b) Check the contactor for smooth operation, correct",
    "contacts where possible. Functionally check the",
    "c) Lubricate the motor contactor in accordance with the",
    "a) Functionally test automatic transfer switches by",
    "normal power. Use a thermographic camera to check for",
    "positions. Check the function of mechanical interlocks",
    "b) Mechanically inspect and exercise the automatic transfer",
    "switch. Check for smooth operation and ensure the",
    "c) Lubricate the automatic transfer switch in accordance",
    "a) Physical condition of fuse housing/base.",
    "b) Operate switches to check for smooth operation and to",
    "confirm that the mechanism is not binding and is",
    "c) Lubricate the switches in accordance with the",
    "d) During the mechanical inspection, check that fuses are",
    "blown fuses, it is good practice to replace all three",
    "a) Trip and Close Coil Voltages.",
    "Measure the voltage required to operate the trip and close",
    "coils. Also verify the trip and close coils are functioning",
    "b) Insulation Resistance.",
    "Apply 1000Vdc for one minute with the circuit breaker",
    "contacts open and closed to measure phase-to-phase and",
    "phase-to-earth resistance for each pole.",
    "Insulation resistance readings must be >100 MΩ.",
    "c) Primary Current Injection Testing.",
    "Circuit breaker with direct tripping can only be tested by",
    "Verify proper operation and response of the protection",
    "functions of the breaker.",
    "The protection relays must pick up and operate at currents",
    "d) Time Travel Record the time travel curve for the circuit",
    "breaker. Compare to manufacturer’s time travel curve as",
    "well as to previous test results to determine if there is",
    "any deterioration in the circuit breaker operating",
    "a) Insulation Resistance.",
    "open and closed to measure phase-to-phase and phase-to-",
    "earth resistance for each pole. Insulation resistance",
    "phase-to-earth resistance for each pole. Insulation",
    "a) Low Resistance.",
    "Measure the resistance of bolted connections using a low",
    "50% between resistance readings. Also check that the",
    "Protection Relays.",
    "a) Secondary injection testing.",
    "Apply 1000Vdc for 1-minute to measure phase-to-earth",
    "Perform secondary current injection testing to check the",
    "functions of the protection relays. Check all protective",
    "functions and verify that the relay settings are in",
    "accordance with the most up to date protection",
  ],
  "3.2.8 Bus Duct / Bus Riser (>800A, <1000 Vac)": [
    "Visual Inspection.",
    "The operator must check that the bus riser is operating in a",
    "clean, cool and dry environment with no abnormal noises,",
    "smells, vibration or heat.",
    "a) Access to bus riser space safely and protected against",
    "b) Arcing can be detected by sound as well as burnt smell.",
    "c) The presence of blistered or blackened paint, the smell",
    "of overheated plastic, and the visual condition of",
    "insulation are good indicators of overheating.",
    "d) Damaged or missing insulators/supports/clamps.",
    "e) Foreign objects, pooled water, leaks, rodents, and",
    "f) Heater settings and operation checks (measurement of",
    "g) Signs of circulating and leakage current.",
    "Thermography.",
    "• Terminations.",
    "• Bolted connections.",
    "• Earth connections",
    "• Tap offs.",
    "(any areas of concern following thermography test must be",
    "Test – Intrusive Maintenance",
    "(breaker, isolators, fusible units etc).",
    "Check the mechanisms for smooth operation and to confirm",
    "Ensure the protection settings / fuse selections are correct.",
    "Measure the resistance of bolted connections using a low",
    "50% between resistance readings. Also check that the",
    "a) Low Resistance.",
    "b) Earthing Resistance and Integrity checks.",
    "c) Torque checks.",
    "d) Operational checks of inline mechanical",
    "components (breaker, isolators, fusible units etc).",
    "Lubricate the mechanisms in accordance with the",
    "Apply 1000Vdc for one minute with the circuit breaker",
    "contacts open and closed to measure phase-to-phase and",
    "phase-to-earth resistance for each pole.",
    "Insulation resistance readings must be >100 MΩ.",
    "a) Insulation Resistance.",
    "contacts open and closed to measure phase-to-phase",
    "and phase-to-earth resistance for each pole.",
  ],
  "3.2.9 Power Factor Correction (<1000 V ac)": [
    "3 months Visual Inspection.",
    "a) Check capacitors, contactors, resistors, reactors and",
    "Capacitor Condition Test.",
    "b) Check capacitor bank for moisture, cleanliness,",
    "c) Check ambient temperature.",
    "d) Check measured power factor and alarms",
    "e) Check power factor trends and harmonic levels.",
    "a) Carry out capacitor condition tests for each phase on",
    "each step. This test shall include measuring the",
    "capacitance of each capacitor.",
    "b) If the value of individual capacitors is found have",
    "Thermography.",
    "b) Bolted connections and terminations.",
    "c) MCCB and fuses.",
    "d) Thyristors or SCR (Silicon-Controlled-Rectifier) modules.",
    "b) Check for damage.",
    "a) Ensure correct operation of discharge resistors as per",
    "c) Check rating(s) are correct for capacitor ratings.",
    "d) Check free operation of MCCB and contactor",
    "e) Ensure fuses are not 'blown'. (Replace with correct",
    "f) Check for evidence of overheating. Renew where",
    "Thermal protection fitted internal to equipment.",
    "a) Check cleanliness.",
    "b) Check settings per manufacturer recommendations.",
    "c) Perform functional tests, including operation of fans.",
    "a) Check operation of capacitor stages.",
    "b) Check for alarms.",
    "c) Check for correct settings.",
  ],
  "3.2.10 Distribution Boards (<1000 V ac)": [
    "3 months Visual Inspection.",
    "a) Check for cleanliness external and internal of panel.",
    "b) Check for signs of exterior damage and corrosion.",
    "c) Check that panels are access controlled.",
    "d) Check for earthing of distribution board panel doors.",
    "e) Check the label and circuit charts are present and",
    "a) Check for accuracy of descriptions. Update schedules as",
    "Ingress Protection.",
    "a) Check that the distribution board’s IP rating is suitable",
    "b) Check for missing gland plates, glands and plugs.",
    "c) Verify that board has protection against accidently",
    "60529. It must not be possible for persons to touch any",
    "a) Check for damage.",
    "b) Check rating(s) where practicable.",
    "c) Check free operation of MCB mechanisms where",
    "d) Check for evidence of overheating. Renew where",
    "Thermal Imaging.",
    "Conduct thermal imaging of distribution boards ensuring",
    "• Solid insulation, Bolted connections, Electrical",
    "• Panel exterior.",
    "• Accessible internal components.",
    "Cable Insulation.",
    "a) Check condition and inspect for signs of overheating.",
    "b) If possible, identify cause of overheating and report.",
    "a) Check all phase, neutral and earth connections and",
    "b) Check tightness of all connections.",
    "c) Cable terminations to be supported by glands or suitable",
    "a) Check for tightness.",
    "b) Check continuity to earth of cable gland.",
    "Earth-Fault Loop Impedance Testing.",
    "Earth loop impedance testing must be carried out at:",
    "a) The origin of the installation (unless value available via",
    "b) At each distribution board.",
    "c) At all fixed equipment.",
    "d) At all socket outlets.",
    "e) 10% of all lighting outlets (choosing farthest point from",
    "f) Furthest point of every radial circuit.",
    "The impedance of the phase-earth loop of a circuit must be",
    "Note: Earth-Fault Loop Impedance testing removes the",
    "need to conduct earth continuity tests because the earth",
    "Residual Current Devices (RCD’s)",
    "a) Check operation via test button (6 months).",
    "b) Test with approved RCD tester (annual).",
  ],
  "3.2.11 AC Induction Motors <1000 V ac <400 kW": [
    "Visually inspect the following:",
    "• Motor foundations.",
    "• Shaft alignment.",
    "• Earth connections.",
    "• Cooling fan cowling",
    "• Air filters.",
    "• Baffles.",
    "• Motor circuit identification labelling is present and",
    "• Corrosion.",
    "• Chemical attack.",
    "• Physical damage.",
    "• Incorrect use of lubrication and over lubrication of",
    "• No undue build-up of dust on the motor.",
    "• Cable & glanding.",
    "• Fixing bolts.",
    "a) Winding Resistance.",
    "Measure the resistance of the motor windings using an",
    "ohmmeter. Check the resistances are balanced.",
    "b) Insulation Resistance.",
    "Measure the winding to earth insulation resistance for each",
    "The insulation resistance reading correct to 40˚C must be",
    "c) Dielectric Absorption.",
    "insulation resistance at 30 seconds to the insulation",
    "a) Check:",
    "• Tightness of all connections.",
    "• For signs of overheating in motor starter cubicle.",
    "• Motor fuse rating and characteristic is correct to",
    "• Operation of motor protection devices.",
    "• Condition of fixed and moving contacts. Replace as",
    "• Control panel functions correctly.",
    "• Indicator lights for correct operation replace as",
    "b) Earth Fault Loop Impedance.",
    "Apply phase to earth link at the motor terminals and",
    "determine the motor circuit earth loop impedance. Confirm",
    "c) Motor Circuit Insulation Resistance.",
    "Measure the phase to earth insulation resistance for each",
    "phase of the motor circuit. This test encompasses both the",
    "supply and motor cables and test separately.",
  ],
  "3.2.12 Hazardous Areas": [
    "are used to check",
    "type of protection",
    "may be visual or",
  ],
  "3.2.12.1 Hazardous Area Inspection Schedules": [
    "Installations (D = Detailed, C = Close, V = Visual).",
    "Check That",
    "Equipment Protection Levels (EPL) / Zone",
  ],
  "11 Bolts, cable entry devices (direct and": [
    "- Physical check.",
    "- Visual check.",
  ],
  "16 Dimensions of flanged joint gaps are:": [
    "– Within the limits in accordance with",
    "– Within maximum values permitted by",
  ],
  "31 Insulation resistance (IR) of the motor": [
    "(D = detailed, C = close, V = visual)",
    "Check That",
  ],
  "4 Stopping boxes and cable boxes are": [
    "- Physical check.",
    "- Visual check.",
  ],
  "2 No undue accumulation of dust and dirt.": [
    "Electrical insulation is clean and dry.",
    "NOTE 1 General: the checks used for equipment using both types of protection",
    "“e” and “d” will be a combination of both columns. For hybrid protections, visual",
    "test equipment.",
    "(D = detailed, C = close, V = visual)",
    "Check That",
    "appropriate to the Equipment Protection Levels (EPL)",
  ],
  "10 Cable glands and blanking elements are the correct": [
    "– Physical check.",
    "– Visual check.",
  ],
  "17 The maximum voltage Um of the associated": [
    "Earth continuity is satisfactory (e.g., connections are",
    "Earth connections maintain the integrity of the type of",
    "protection.",
    "Check That",
    "Insulation resistance is satisfactory.",
  ],
  "13 Cables not in use are correctly terminated.": [
    "weather, vibration and other adverse factors.",
    "(D = detailed, C = close, V = visual)",
    "Check That",
    "Equipment is appropriate to the Equipment Protection",
    "- Physical check.",
    "- Visual check.",
  ],
  "3.2.13 Emergency Lighting Systems": [
    "• Switch each luminaire and each internally",
    "rated duration test shall be recorded.",
    "the battery. This simulates a failure of the supply",
    "• For central battery systems, the correct operation",
    "• Each luminaire and internally illuminated sign shall",
    "be tested as per monthly test but for its full rated",
    "• The supply of the normal lighting shall be restored,",
    "• The date of the test and its results shall be",
    "• Lux measurements to ensure it meets the",
    "• In locations where personnel are expected to work",
  ],
  "REQUIREMENTS": [
    "• The UPS asset must be included in computerised maintenance",
    "o Type of battery / Battery code.",
    "o Year of installation of the battery.",
    "• The UPS must be in suitable ambient conditions within",
    "Perform Visual Inspection",
    "UPS Battery Test",
    "• Inspect the UPS solution to ensure that unit is",
    "• Check UPS has no outstanding alarms. Any alarms",
    "• Check UPS is clean and free of dust. Pay attention to",
    "any vents on UPS. Clean and replace any filters as",
    "• Perform battery test and maintenance as per item",
    "3.2.16 accordingly with the type of battery installed on",
    "the UPS system.",
    "• During the assets 7th year (asset is over 7 years old)",
    "schedule replacement of UPS.",
  ],
  "MANDATORY REQUIREMENTS": [
    "• The UPS must be included in computerised maintenance",
    "o Type of battery / Battery code.",
    "o Year of installation of the battery.",
    "Perform Visual Inspection",
    "• The UPS must be in a clean (free from excessive dust)",
    "• Inspect the UPS. Ensure all components are clean and",
    "• Check UPS fans and filters. Replace / clean filters as",
    "• Verify and document that the system’s environment is",
    "o UPS airflow and that there is no dust",
    "contamination within the UPS.",
    "• Inspect all power and control wire termination points as",
    "well as all UPS system components.",
    "• Determine components with the UPS that are",
    "• Check UPS event and alarm logs.",
    "• Verify that input, output and bypass voltage and current",
    "• Verify that the installed communication options are",
    "• Verify on battery operation and transfer to and from",
    "Check parallel operation performance when applicable.",
    "• Verify and implement all required firmware upgrades.",
    "• Check all circuit board revisions and update as required.",
    "Replace components at OEM recommended intervals. E.g.",
    "UPS Battery Test",
    "• Perform battery test and maintenance as per item",
    "3.2.16 accordingly with the type of battery installed on",
    "the UPS system.",
    "UPS mid-life overhaul",
    "• Follow manufacturer recommendations for the",
    "replacement of UPS system components.",
    "UPS replacement",
    "• During the assets 12th year (asset is over 12 years old)",
    "schedule replacement of UPS.",
  ],
  "3.2.16 Battery Systems": [
    "Visual inspection of Charger Unit",
    "Check cleanliness. Check indicators and meters. Check",
    "alarm logs, if available. Check cooling fan operation",
    "Check power capacitors for exterior signs of degradation,",
    "Check and record charger voltage and current. Check",
    "1 to 3 yrs. Perform a load discharge test to frequency and instructions",
    "Replace the battery when its measured capacity approaches",
    "Check and record charger voltage and current. Check and",
    "record ambient temperature, and for evidence of corrosion,",
    "Perform a load discharge test as per manufacturing",
  ],
  "3.2.17 Variable Speed Drives": [
    "Visual Inspection",
    "• Check for cleanliness external and internal to panel,",
    "particularly around ventilation openings and fans – clean",
    "• Check for signs of damage and corrosion.",
    "• Check controller for alarms.",
    "• Check ambient temperature and any signs of",
    "Ingress Protection",
    "• Check correct and permanent label is fitted.",
    "• Check that the drive’s IP rating is suitable for the",
    "• Check for missing gland plates, glands and plugs.",
    "• Verify that panel has protection against accidental",
    "• Check filters and clean or replace, as necessary.",
    "• Check correct operation of fans.",
    "Thermal Imaging",
    "Conduct thermal imaging ensuring the following items are",
    "• Panel exterior.",
    "• Accessible internal components, cables.",
    "• Carry out capacitor condition test. This test shall include",
    "measuring the capacitance of each capacitor. If the",
    "more than 10% isolate drive and replace.",
    "• If the drive contains plastic can capacitors that are older",
    "than 10 years isolate the drive and replace.",
    "• Check all phase, and earth connections and",
    "• Check tightness of all connections.",
    "• Replace fans in line with manufacturer",
    "• Cable terminations to be supported by glands or suitable",
  ],
  "3.2.18 Fire Detection and Fire Alarm Systems": [
    "• A manual call point must be operated during normal",
    "transmitted. The test should be carried out at",
    "• In systems with staged alarms incorporating an “Alert”",
    "• In facilities where some employees only work during",
    "normally tested (e.g., shift workers), an additional test(s)",
    "• A different manual call point must be used at the time of",
    "every weekly test, so that all manual call points in the",
    "system with 150 manual call points, the user will test",
    "• The result of the weekly test and the identity of the",
    "• The duration for which any fire alarm signal is given",
    "the time of the weekly test by the user should not",
    "fire at the time of the weekly test, occupants will be",
    "Periodic Inspection and Test of the System",
    "• The system logbook must be examined. It must be",
    "• A visual inspection must be made to check whether",
    "• The records of false alarms must be checked. The rate",
    "• The fire alarm functions of the control and indicating",
    "• The operation of the fire alarm devices must be",
    "• All controls and visual indicators at control and",
    "• The operation of any facility for automatic transmission",
    "• All ancillary functions of the control and indicating",
    "• All fault indicators and their circuits should be checked,",
    "• All printers must be tested to ensure that they operate",
    "• Radio systems of all types must be serviced in",
    "• On completion of the work, any outstanding defects",
    "Annual Inspection and Test of the System",
    "• The switch mechanism of every manual call point",
    "element, insertion of a test key or operation of the",
    "• All automatic fire detectors and remote detectors",
    "• Every heat detector must be functionally tested by",
    "integrating line detectors). Special test",
    "• Point smoke detectors must be functionally tested by",
    "• Optical beam smoke detectors must be functionally",
    "filter, smoke or simulated smoke.",
    "• Aspirating fire detection systems must be",
    "• Carbon monoxide fire detectors must be functionally",
    "• Flame detectors must be functionally tested by a",
    "• In fire detection systems that enable analogue",
    "• Multi-sensor detectors must be operated by a",
    "confirmed that visual fire alarm devices are not",
    "clean.",
    "• A visual inspection must be made to confirm that all",
    "• The standby power supply capacity must be checked",
    "• Interlocks to equipment such as door access control",
    "record of the inspection and test must be made on",
    "Battery Inspection",
    "Perform battery test and maintenance as per item 3.2.16",
    "accordingly with the type of battery installed on the system.",
    "Battery Test/Maintenance",
    "Perform battery test and maintenance as per item",
    "3.2.16 accordingly with the type of battery installed",
  ],
  "4 Roles & Responsibility": [
    "• A Haleon employee in a local senior leadership",
    "Function SME",
    "• Able to control, direct or influence resources, both",
  ],
  "5.1 Regulations / External References": [
    "• IEC 60364 - Electrical Installations for Buildings",
    "• IEC 60529 – Degrees of protection provided by enclosures (IP",
    "• IEC 60079 – Explosive Atmosphere Standards Series",
  ],
};


/**
 * Return a flat list of all controls (strings).
 */
export function allControls() {
  return Object.values(TSD_FULL_CONTROLS).flat();
}

/**
 * Return controls for a given section title (exact match).
 */
export function controlsForSection(sectionTitle) {
  return TSD_FULL_CONTROLS[sectionTitle] || [];
}

/**
 * Search controls by a keyword (case-insensitive).
 */
export function searchControls(keyword) {
  if (!keyword) return [];
  const k = keyword.toLowerCase();
  const results = [];
  for (const [section, items] of Object.entries(TSD_FULL_CONTROLS)) {
    for (const line of items) {
      if (line.toLowerCase().includes(k)) {
        results.push({ section, line });
      }
    }
  }
  return results;
}


/**
 * Integrated facade that combines the original library with the exhaustive, line-by-line control set.
 * - Preserves all original exports.
 * - Adds `TSD_FULL_CONTROLS` (by section), `allControls`, `controlsForSection`, `searchControls`.
 * - Adds `getIntegratedControls()` to retrieve a consolidated structure useful for CMMS binding.
 */
export function getIntegratedControls() {
  // If the original library defines structured equipment/tasks, we expose both:
  const sections = TSD_FULL_CONTROLS;
  const controls = allControls();

  return {
    sections,          // { sectionTitle: [ "control line", ... ] }
    controls,          // [ "control line", ... ]
  };
}

/**
 * Generate stable IDs for controls (useful for CMMS field keys, diffing, etc.).
 * ID format: `${crc32(section)}-${index}-${crc32(line)}`
 */
export function controlIds() {
  function crc32(str) {
    let c = 0 ^ -1;
    for (let i = 0; i < str.length; i++) {
      c = (c >>> 8) ^ CRC_TABLE[(c ^ str.charCodeAt(i)) & 0xFF];
    }
    return (c ^ -1) >>> 0;
  }
  const CRC_TABLE = (() => {
    const t = new Uint32Array(256);
    for (let n = 0; n < 256; n++) {
      let c = n;
      for (let k = 0; k < 8; k++) {
        c = c & 1 ? 0xEDB88320 ^ (c >>> 1) : (c >>> 1);
      }
      t[n] = c >>> 0;
    }
    return t;
  })();

  const ids = [];
  let idx = 0;
  for (const [section, items] of Object.entries(TSD_FULL_CONTROLS)) {
    const sHash = crc32(section).toString(16);
    for (let i = 0; i < items.length; i++) {
      const line = items[i];
      const lHash = crc32(line).toString(16);
      ids.push({ id: `${sHash}-${idx}-${lHash}`, section, line });
      idx++;
    }
  }
  return ids;
}

// === END: Auto-integrated block ===
